/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestioninventariomercado.Ventanas;
import com.mycompany.gestioninventariomercado.Clases.Tienda;
import javax.swing.table.DefaultTableModel;
import java.awt.Desktop;
import java.io.File;
/**
 *
 * @author diazv
 */
public class VentanaListarProductos extends javax.swing.JFrame {

    /**
     * Creates new form ModificarProducto
     */
    private Tienda tienda;
    public VentanaListarProductos(Tienda tienda) {
        this.tienda = tienda;
        initComponents();
        String texto = tienda.toString();
        String [] arrayTexto = texto.split("\n");
        DefaultTableModel modelo = (DefaultTableModel) TablaLista.getModel();
        
        for(int i = 0; i< arrayTexto.length;i++){
            String[] fila = arrayTexto[i].split(",");
            modelo.addRow(fila);
        }
        
        this.filtroSecciones.addItem("Todas");
        for(int i = 0; i < this.tienda.getListSecciones().size();i++){
            this.filtroSecciones.addItem(this.tienda.getListSecciones().get(i).getNombreSeccion());
        }
        
    }
    public void refrescarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) TablaLista.getModel();
        modelo.setRowCount(0); // limpia la tabla

        String texto = tienda.toString();
        String[] arrayTexto = texto.split("\n");
        String seccionSeleccionada = (String) filtroSecciones.getSelectedItem();

        for (String linea : arrayTexto) {
            String[] fila = linea.split(",");
            if (seccionSeleccionada.equals("Todas") || fila[0].equals(seccionSeleccionada)) {
                modelo.addRow(fila);
            }
        }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLista = new javax.swing.JTable();
        botonSalir = new javax.swing.JButton();
        botonImprimir = new javax.swing.JButton();
        botonListarVencidos = new javax.swing.JButton();
        filtroSecciones = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seccion", "Codigo", "Nombre", "Cantidad", "Vendedor", "Precio Compra", "Fecha de Vencimiento", "Cantidad Por Lote"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaLista);

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonImprimir.setText("Imprimir en txt");
        botonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImprimirActionPerformed(evt);
            }
        });

        botonListarVencidos.setText("Listar Productos Vencidos");
        botonListarVencidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarVencidosActionPerformed(evt);
            }
        });

        filtroSecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroSeccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(botonImprimir)
                .addGap(35, 35, 35)
                .addComponent(botonListarVencidos)
                .addGap(133, 133, 133)
                .addComponent(filtroSecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir)
                    .addComponent(botonImprimir)
                    .addComponent(botonListarVencidos)
                    .addComponent(filtroSecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImprimirActionPerformed
        // TODO add your handling code here:
        
        try {
            tienda.generarReporte();
            File archivo = new File("reporte.txt");
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(archivo);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_botonImprimirActionPerformed

    private void botonListarVencidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarVencidosActionPerformed
        // TODO add your handling code here:
        VentanaListarProductosVencidos ventanaVencidos = new VentanaListarProductosVencidos(this.tienda);
        ventanaVencidos.setVisible(true);

        ventanaVencidos.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            refrescarTabla(); 
        }
});
        
    }//GEN-LAST:event_botonListarVencidosActionPerformed

    private void filtroSeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroSeccionesActionPerformed

    String seccionSeleccionada = (String) filtroSecciones.getSelectedItem();
    
    
    DefaultTableModel modelo = (DefaultTableModel) TablaLista.getModel();
    modelo.setRowCount(0);

    String texto = tienda.toString();
    String[] arrayTexto = texto.split("\n");

    
    for (int i = 0; i < arrayTexto.length; i++) {
        String[] fila = arrayTexto[i].split(","); 
        /*Se imprime el producto si es de la seccion que se indica o si las indicaciones es que se imprima todo*/
        if (seccionSeleccionada.equals("Todas") || fila[0].equals(seccionSeleccionada)) {
            modelo.addRow(fila);
        }
    }
    }//GEN-LAST:event_filtroSeccionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaListarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaListarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaListarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaListarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        Tienda tienda = new Tienda("");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaListarProductos(tienda).setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaLista;
    private javax.swing.JButton botonImprimir;
    private javax.swing.JButton botonListarVencidos;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> filtroSecciones;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
