/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestioninventariomercado.Ventanas;

import com.mycompany.gestioninventariomercado.Clases.Producto;
import com.mycompany.gestioninventariomercado.Clases.ProductoPereciblePorLote;
import com.mycompany.gestioninventariomercado.Clases.ProductoPerecible;
import com.mycompany.gestioninventariomercado.Clases.ProductoPorLote;
import com.mycompany.gestioninventariomercado.Clases.Seccion;
import com.mycompany.gestioninventariomercado.Clases.Tienda;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import com.mycompany.gestioninventariomercado.Exepciones.ExcepcionLimiteNumerico;
import com.mycompany.gestioninventariomercado.Exepciones.ExcepcionNumNegativo;
import com.mycompany.gestioninventariomercado.Exepciones.VerificadorNumero;
import com.mycompany.gestioninventariomercado.Exepciones.ExcepcionLimiteDecimales;
import com.mycompany.gestioninventariomercado.Exepciones.VerificadorString;
import com.mycompany.gestioninventariomercado.Exepciones.ExcepcionLimiteString;


/**
 *
 * @author diazv
 */
public class VentanaAgregarProducto extends javax.swing.JFrame {

    /**
     * Creates new form AgregarItem
     */
    private Tienda tienda;
    
    
    public VentanaAgregarProducto(Tienda tienda) {
        this.tienda = tienda;
        
        initComponents();
        this.inputSeccion.addItem("Nueva Seccion");
        for(int i = 0; i < this.tienda.getListSecciones().size();i++){
            this.inputSeccion.addItem(this.tienda.getListSecciones().get(i).getNombreSeccion());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputCodigo = new javax.swing.JTextPane();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        TextoError = new javax.swing.JLabel();
        esPerecible = new javax.swing.JCheckBox();
        esLote = new javax.swing.JCheckBox();
        TextoSeccion = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        textoCantidad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textoPrecioCompra = new javax.swing.JLabel();
        labelCaducidad = new javax.swing.JLabel();
        labelLote = new javax.swing.JLabel();
        inputCantidad = new javax.swing.JTextField();
        inputNombre = new javax.swing.JTextField();
        inputVendedor = new javax.swing.JTextField();
        inputPrecioCompra = new javax.swing.JTextField();
        inputFechaVencimiento = new javax.swing.JTextField();
        inputCantidadPorLote = new javax.swing.JTextField();
        inputSeccion = new javax.swing.JComboBox<>();
        textoNuevaSeccion = new javax.swing.JLabel();
        inputNuevaSeccion = new javax.swing.JTextField();
        textoCantidadPorLote = new javax.swing.JLabel();
        textoVencimiento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Agregar Productos");

        textoCodigo.setText("Codigo Producto:");

        jScrollPane3.setViewportView(inputCodigo);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Agregar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        TextoError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoError.setText(".");

        esPerecible.setText("Es un Perecible?");
        esPerecible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esPerecibleActionPerformed(evt);
            }
        });

        esLote.setText("El Producto Viene en un lote O paquete?");
        esLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esLoteActionPerformed(evt);
            }
        });

        TextoSeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoSeccion.setText("Seccion:");

        textoNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoNombre.setText("Nombre:");

        textoCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCantidad.setText("Cantidad:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Vendedor:");

        textoPrecioCompra.setText("Precio de Compra:");

        inputCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputCantidad.setToolTipText("");
        inputCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCantidadActionPerformed(evt);
            }
        });

        inputNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputNombre.setToolTipText("");
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });

        inputVendedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputVendedor.setToolTipText("");
        inputVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputVendedorActionPerformed(evt);
            }
        });

        inputPrecioCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputPrecioCompra.setToolTipText("");
        inputPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPrecioCompraActionPerformed(evt);
            }
        });

        inputFechaVencimiento.setEditable(false);
        inputFechaVencimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputFechaVencimiento.setToolTipText("");
        inputFechaVencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFechaVencimientoActionPerformed(evt);
            }
        });

        inputCantidadPorLote.setEditable(false);
        inputCantidadPorLote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputCantidadPorLote.setToolTipText("");
        inputCantidadPorLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCantidadPorLoteActionPerformed(evt);
            }
        });

        inputSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSeccionActionPerformed(evt);
            }
        });

        textoNuevaSeccion.setText("Nombre Nueva Seccion:");

        textoCantidadPorLote.setText("Cuantos Productos vienen en el paquete o lote?");

        textoVencimiento.setText("Fecha de Vencimiento (Formato dd/mm/yyyy):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoNuevaSeccion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextoSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(inputSeccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(122, 122, 122)
                                .addComponent(esPerecible, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(esLote))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(inputNuevaSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(labelLote, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textoVencimiento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textoCantidadPorLote)
                                    .addGap(18, 18, 18)
                                    .addComponent(inputCantidadPorLote, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCodigo)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(102, 102, 102))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(inputVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoPrecioCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(inputPrecioCompra)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(labelCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextoError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAceptar)))
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextoSeccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textoPrecioCompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textoCantidad)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoNuevaSeccion)
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCaducidad)
                    .addComponent(labelLote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNuevaSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(esPerecible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoVencimiento))
                .addGap(18, 18, 18)
                .addComponent(esLote)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCantidadPorLote)
                    .addComponent(inputCantidadPorLote, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        if(inputCodigo.getText().isEmpty() ){
            TextoError.setText("Ingrese un codigo");
            TextoError.setForeground(Color.red);
            return;
        }
        Producto nuevo; 

        if (esPerecible.isSelected() && esLote.isSelected()) {
            nuevo = new ProductoPereciblePorLote();
        } else if (esLote.isSelected()) {
            nuevo = new ProductoPorLote();
        } else if (esPerecible.isSelected()) {
            nuevo = new ProductoPerecible();
        } else {
            nuevo = new Producto();
        }
        
        
        try{
            int codigo = Integer.parseInt(inputCodigo.getText());
            int cantidad = Integer.parseInt(inputCantidad.getText());
            float precio = Float.parseFloat(inputPrecioCompra.getText());
            String nombre = inputNombre.getText();
            String vendedor = inputVendedor.getText();
            
            VerificadorNumero.verificar(codigo);
            VerificadorNumero.verificar(cantidad);
            VerificadorNumero.verificar(precio);
            
            VerificadorString.verificar(nombre);
            VerificadorString.verificar(vendedor);
            
            nuevo.setNombreProducto(nombre);
            nuevo.setCantidadProducto(cantidad);
            nuevo.setVendedor(vendedor);
            nuevo.setPrecioCompra(precio);
            nuevo.setCodigo(codigo);
            
            if (nuevo instanceof ProductoPereciblePorLote) {
                ProductoPereciblePorLote p = (ProductoPereciblePorLote) nuevo;
                int cantidadLote = Integer.parseInt(inputCantidadPorLote.getText());
                VerificadorNumero.verificar(cantidadLote);
                p.setCantidadLote(cantidadLote);
                p.setFechaVencimiento(LocalDate.parse(inputFechaVencimiento.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy")));
            } else if (nuevo instanceof ProductoPerecible) {
                ProductoPerecible p = (ProductoPerecible) nuevo;
                
                p.setFechaVencimiento(LocalDate.parse(inputFechaVencimiento.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy")));
            } else if (nuevo instanceof ProductoPorLote) {
                ProductoPorLote p = (ProductoPorLote) nuevo;
                int cantidadLote = Integer.parseInt(inputCantidadPorLote.getText());
                VerificadorNumero.verificar(cantidadLote);
                p.setCantidadLote(cantidadLote);
            }
            
            
            String inputS = (String) this.inputSeccion.getSelectedItem();
            if(inputS.equals("Nueva Seccion")){
               Seccion sec = new Seccion(this.inputNuevaSeccion.getText());
               this.tienda.agregarSeccion(sec);
               inputS = this.inputNuevaSeccion.getText();
            }
            if(tienda.getSeccion(inputS).agregarProducto(Integer.parseInt(inputCodigo.getText()), nuevo)){
                this.dispose();
            }else{
                TextoError.setText("El codigo de producto ingresado ya existe");
                TextoError.setForeground(Color.red);
            }
        }catch (NumberFormatException e) {
            this.TextoError.setText("Ha ingresado un valor erroneo en una casilla");
            this.TextoError.setForeground(Color.red);
        }catch (java.time.format.DateTimeParseException e) {
            this.TextoError.setText("Formato de fecha incorrecto, use dd/MM/yyyy");
            this.TextoError.setForeground(Color.red);
        }catch (ExcepcionNumNegativo | ExcepcionLimiteNumerico | ExcepcionLimiteDecimales|ExcepcionLimiteString e) {
            this.TextoError.setText(e.getMessage());
            this.TextoError.setForeground(Color.red);
        } 
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void esPerecibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esPerecibleActionPerformed
        // TODO add your handling code here:
        if (esPerecible.isSelected()) {
            inputFechaVencimiento.setEditable(true);
        }else
        {
            inputFechaVencimiento.setEditable(false);
        }
    }//GEN-LAST:event_esPerecibleActionPerformed

    private void esLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esLoteActionPerformed
        // TODO add your handling code here:
        if (esLote.isSelected()) {
            inputCantidadPorLote.setEditable(true);
        }else
        {
            inputCantidadPorLote.setEditable(false);
        }
    }//GEN-LAST:event_esLoteActionPerformed

    private void inputCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCantidadActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputVendedorActionPerformed

    private void inputPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPrecioCompraActionPerformed

    private void inputFechaVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFechaVencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFechaVencimientoActionPerformed

    private void inputCantidadPorLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCantidadPorLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCantidadPorLoteActionPerformed

    private void inputSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSeccionActionPerformed
        // TODO add your handling code here:
        String seleccionado = (String)this.inputSeccion.getSelectedItem();
        if(seleccionado.equalsIgnoreCase("Nueva Seccion")){
            this.inputNuevaSeccion.setEditable(true);
        }else{
            this.inputNuevaSeccion.setEditable(false);
        }
        
        
    }//GEN-LAST:event_inputSeccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoError;
    private javax.swing.JLabel TextoSeccion;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JCheckBox esLote;
    private javax.swing.JCheckBox esPerecible;
    private javax.swing.JTextField inputCantidad;
    private javax.swing.JTextField inputCantidadPorLote;
    private javax.swing.JTextPane inputCodigo;
    private javax.swing.JTextField inputFechaVencimiento;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputNuevaSeccion;
    private javax.swing.JTextField inputPrecioCompra;
    private javax.swing.JComboBox<String> inputSeccion;
    private javax.swing.JTextField inputVendedor;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelCaducidad;
    private javax.swing.JLabel labelLote;
    private javax.swing.JLabel textoCantidad;
    private javax.swing.JLabel textoCantidadPorLote;
    private javax.swing.JLabel textoCodigo;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoNuevaSeccion;
    private javax.swing.JLabel textoPrecioCompra;
    private javax.swing.JLabel textoVencimiento;
    // End of variables declaration//GEN-END:variables
}
