/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestioninventariomercado.Ventanas;

import com.mycompany.gestioninventariomercado.Clases.Producto;
import com.mycompany.gestioninventariomercado.Clases.ProductoPerecible;
import com.mycompany.gestioninventariomercado.Clases.ProductoPereciblePorLote;
import com.mycompany.gestioninventariomercado.Clases.ProductoPorLote;
import com.mycompany.gestioninventariomercado.Clases.Tienda;
import java.awt.Color;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author diazv
 */
public class VentanaEliminarProductos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEliminarProductos
     */
    private Tienda tienda;
    private int codigoBuscado;
    public VentanaEliminarProductos(Tienda tienda) {
        initComponents();
        this.tienda = tienda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        textoCodigo = new javax.swing.JLabel();
        inputCodigo = new javax.swing.JTextField();
        botonSalir = new javax.swing.JButton();
        textoError = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Eliminar Productos");
        Titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seccion", "Codigo", "Nombre", "Cantidad", "Vendedor", "PrecioCompra", "Fecha Caducidad", "Cantidad Por Lote"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProducto);

        textoCodigo.setText("Codigo Producto:");

        inputCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCodigoActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        textoError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoError.setText(".");

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(textoCodigo)
                .addGap(18, 18, 18)
                .addComponent(inputCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(324, 324, 324))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonBuscar)
                .addGap(373, 373, 373))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(botonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(textoError, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(botonEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCodigo)
                    .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(botonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(textoError)
                .addGap(18, 18, 18)
                .addComponent(botonEliminar)
                .addGap(21, 21, 21)
                .addComponent(botonSalir)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCodigoActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
        // Si no hay producto buscado, no tiene sentido eliminar
    if (this.codigoBuscado == 0) {
        textoError.setText("Primero debe buscar un producto.");
        textoError.setForeground(Color.red);
        return;
    }

    Producto buscado = this.tienda.getProductoEnSeccionPorCodigo(this.codigoBuscado);

    if (buscado == null) {
        textoError.setText("El producto ya no existe en la tienda.");
        textoError.setForeground(Color.red);
        return;
    }

    // Obtener la sección del producto
    String nombreSeccion = this.tienda.getNombreSeccionDeProducto(this.codigoBuscado);

    if (nombreSeccion == null) {
        textoError.setText("No se encontró la sección del producto.");
        textoError.setForeground(Color.red);
        return;
    }

    // Eliminar el producto desde la sección
    boolean eliminado = this.tienda.getSeccion(nombreSeccion).eliminarProducto(this.codigoBuscado);

    if (eliminado) {
        // Limpiar tabla y mostrar éxito
        DefaultTableModel modelo = (DefaultTableModel) this.tablaProducto.getModel();
        modelo.setRowCount(0);
        textoError.setText("Producto eliminado correctamente.");
        textoError.setForeground(Color.GREEN);
        this.codigoBuscado = 0; // reset
    } else {
        textoError.setText("Error al eliminar el producto.");
        textoError.setForeground(Color.red);
    }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        Producto buscado;
    try {
        buscado = this.tienda.getProductoEnSeccionPorCodigo(
            Integer.parseInt(this.inputCodigo.getText())
        );
    } catch (NumberFormatException e) {
        textoError.setText("Código inválido.");
        textoError.setForeground(Color.red);
        return;
    }

    if (buscado == null) {
        textoError.setText("El código de producto ingresado no existe.");
        textoError.setForeground(Color.red);
        return;
    }
    
       DefaultTableModel modelo = (DefaultTableModel) this.tablaProducto.getModel();
        modelo.setRowCount(0); 
        String[] fila = new String[8];

    try {
        // Columna 0: seccion
        fila[0] = this.tienda.getNombreSeccionDeProducto(buscado.getCodigo());
        // Columnas 1-5: datos básicos del producto
    
        fila[1] = String.valueOf(buscado.getCodigo());
        fila[2] = buscado.getNombre();
        fila[3] = String.valueOf(buscado.getCantidad());
        fila[4] = buscado.getVendedor();
        fila[5] = String.valueOf(buscado.getPrecioCompra());

        // Columnas 6-7 según tipo de producto
        if (buscado instanceof ProductoPereciblePorLote) {
            ProductoPereciblePorLote p = (ProductoPereciblePorLote) buscado;
            fila[6] = p.getFechaVencimiento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            fila[7] = String.valueOf(p.getCantidadLote());
        } else if (buscado instanceof ProductoPerecible) {
            ProductoPerecible p = (ProductoPerecible) buscado;
            fila[6] = p.getFechaVencimiento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            fila[7] = "";
        } else if (buscado instanceof ProductoPorLote) {
            ProductoPorLote p = (ProductoPorLote) buscado;
            fila[6] = "";
            fila[7] = String.valueOf(p.getCantidadLote());
        } else { // Producto normal
            fila[6] = "";
            fila[7] = "";
        }

        modelo.addRow(fila);

        // Parseo del código ingresado
        this.codigoBuscado = Integer.parseInt(this.inputCodigo.getText());
        
    }catch (NumberFormatException e) {
    // Si el código o cantidad vienen con letras
    this.textoError.setText("Formato de número incorrecto (solo se permiten números)");
    this.textoError.setForeground(Color.red);
}
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Tienda tienda = new Tienda("");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEliminarProductos(tienda).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField inputCodigo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JLabel textoCodigo;
    private javax.swing.JLabel textoError;
    // End of variables declaration//GEN-END:variables
}
