/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestioninventariomercado;

import com.mycompany.gestioninventariomercado.Clases.Tienda;
import com.mycompany.gestioninventariomercado.Ventanas.VentanaSecciones;
import com.mycompany.gestioninventariomercado.Ventanas.VentanaListarProductos;
import com.mycompany.gestioninventariomercado.Ventanas.VentanaBuscarProducto;
import com.mycompany.gestioninventariomercado.Ventanas.VentanaAgregarProducto;


import java.io.IOException;
/**
 *
 * @author diazv
 */
public class VentanaMenuPrincipalGrafico extends javax.swing.JFrame {

    /**
     * Creates new form AgregarItem
     */
    private Tienda tienda;
    public VentanaMenuPrincipalGrafico(Tienda tienda) {
        initComponents();
        this.tienda = tienda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonGuardar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProductos = new javax.swing.JMenu();
        agregarEliminarProducto = new javax.swing.JMenuItem();
        listarProductos = new javax.swing.JMenuItem();
        buscarModificarProducto = new javax.swing.JMenuItem();
        menuSecciones = new javax.swing.JMenu();
        editarSecciones = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        confirmarSalida = new javax.swing.JMenuItem();

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar3.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar3.add(jMenu9);

        jMenu10.setText("File");
        jMenuBar4.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar4.add(jMenu11);

        jMenuItem9.setText("jMenuItem9");

        jMenuItem10.setText("jMenuItem10");

        jMenuItem11.setText("jMenuItem11");

        jMenu4.setText("File");
        jMenuBar5.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar5.add(jMenu5);

        jMenu12.setText("File");
        jMenuBar6.add(jMenu12);

        jMenu13.setText("Edit");
        jMenuBar6.add(jMenu13);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eliga su Operación con las Opciones en la esquina superior izquierda");

        jLabel2.setText("SISTEMA PARA GESTIONAR UN SUPERMERCADO");

        BotonGuardar.setText("Guardar Cambios");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        menuProductos.setText("Productos");

        agregarEliminarProducto.setText("Agregar/Eliminar Producto");
        agregarEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEliminarProductoActionPerformed(evt);
            }
        });
        menuProductos.add(agregarEliminarProducto);

        listarProductos.setText("Listar Productos");
        listarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProductosActionPerformed(evt);
            }
        });
        menuProductos.add(listarProductos);

        buscarModificarProducto.setText("Buscar y/o Modificar Producto");
        buscarModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarModificarProductoActionPerformed(evt);
            }
        });
        menuProductos.add(buscarModificarProducto);

        jMenuBar1.add(menuProductos);

        menuSecciones.setText("Secciones");

        editarSecciones.setText("Editar Secciones");
        editarSecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarSeccionesActionPerformed(evt);
            }
        });
        menuSecciones.add(editarSecciones);

        jMenuBar1.add(menuSecciones);

        menuSalir.setText("Salir");

        confirmarSalida.setText("Confirmar");
        confirmarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarSalidaActionPerformed(evt);
            }
        });
        menuSalir.add(confirmarSalida);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonGuardar)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(BotonGuardar)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEliminarProductoActionPerformed
        // TODO add your handling code here:
        VentanaAgregarProducto ventanaAgregar = new VentanaAgregarProducto(this.tienda,this);
        ventanaAgregar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agregarEliminarProductoActionPerformed

    private void confirmarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarSalidaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_confirmarSalidaActionPerformed

    private void editarSeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarSeccionesActionPerformed
        // TODO add your handling code here:
        VentanaSecciones ventanaSecciones = new VentanaSecciones(this.tienda);
        ventanaSecciones.setVisible(true);
    }//GEN-LAST:event_editarSeccionesActionPerformed

    private void buscarModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarModificarProductoActionPerformed
        // TODO add your handling code here:
        VentanaBuscarProducto ventanaBuscar = new VentanaBuscarProducto(this.tienda);
        ventanaBuscar.setVisible(true);
    }//GEN-LAST:event_buscarModificarProductoActionPerformed

    private void listarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProductosActionPerformed
        // TODO add your handling code here:
        VentanaListarProductos ventanaListar = new VentanaListarProductos(this.tienda);
        ventanaListar.setVisible(true);
    }//GEN-LAST:event_listarProductosActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        // TODO add your handling code here:
        try {
            this.tienda.guardarDatos("inventario.txt");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BotonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipalGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipalGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipalGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipalGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        Tienda tienda = new  Tienda("");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaMenuPrincipalGrafico(tienda).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JMenuItem agregarEliminarProducto;
    private javax.swing.JMenuItem buscarModificarProducto;
    private javax.swing.JMenuItem confirmarSalida;
    private javax.swing.JMenuItem editarSecciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem listarProductos;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenu menuSecciones;
    // End of variables declaration//GEN-END:variables
}
