/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestioninventariomercado;

import java.awt.Color;
import java.util.HashSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diazv
 */
public class VentanaAgregarProducto extends javax.swing.JFrame {

    /**
     * Creates new form AgregarItem
     */
    private Tienda tienda;
    private VentanaMenuPrincipalGrafico ventanaPrincipal;
    
    public VentanaAgregarProducto(Tienda tienda, VentanaMenuPrincipalGrafico ventanaPrincipal) {
        this.tienda = tienda;
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputCodigo = new javax.swing.JTextPane();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        TextoError = new javax.swing.JLabel();
        esPerecible = new javax.swing.JCheckBox();
        esLote = new javax.swing.JCheckBox();
        inputSeccion = new javax.swing.JTextField();
        TextoSeccion = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        textoCantidad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textoPrecioCompra = new javax.swing.JLabel();
        labelCaducidad = new javax.swing.JLabel();
        labelLote = new javax.swing.JLabel();
        inputCantidad = new javax.swing.JTextField();
        inputNombre = new javax.swing.JTextField();
        inputVendedor = new javax.swing.JTextField();
        inputPrecioCompra = new javax.swing.JTextField();
        inputCaducidad = new javax.swing.JTextField();
        inputLote = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Agregar Productos");

        textoCodigo.setText("Codigo Producto:");

        jScrollPane3.setViewportView(inputCodigo);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Agregar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        TextoError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoError.setText(".");

        esPerecible.setText("Es un Perecible?");
        esPerecible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esPerecibleActionPerformed(evt);
            }
        });

        esLote.setText("Es un Lote?");
        esLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esLoteActionPerformed(evt);
            }
        });

        inputSeccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputSeccion.setToolTipText("");
        inputSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSeccionActionPerformed(evt);
            }
        });

        TextoSeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoSeccion.setText("Seccion");

        textoNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoNombre.setText("Nombre");

        textoCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCantidad.setText("Cantidad");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Vendedor");

        textoPrecioCompra.setText("PrecioCompra");

        inputCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputCantidad.setToolTipText("");
        inputCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCantidadActionPerformed(evt);
            }
        });

        inputNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputNombre.setToolTipText("");
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });

        inputVendedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputVendedor.setToolTipText("");
        inputVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputVendedorActionPerformed(evt);
            }
        });

        inputPrecioCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputPrecioCompra.setToolTipText("");
        inputPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPrecioCompraActionPerformed(evt);
            }
        });

        inputCaducidad.setEditable(false);
        inputCaducidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputCaducidad.setToolTipText("");
        inputCaducidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCaducidadActionPerformed(evt);
            }
        });

        inputLote.setEditable(false);
        inputLote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputLote.setToolTipText("");
        inputLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonCancelar)
                .addGap(185, 185, 185)
                .addComponent(botonAceptar)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(labelCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelLote, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(inputSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextoSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(129, 129, 129))
                                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textoCodigo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(TextoError, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(esLote, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(inputCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(esPerecible, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(inputLote, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoCodigo)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoSeccion)
                    .addComponent(textoNombre)
                    .addComponent(textoCantidad)
                    .addComponent(jLabel6)
                    .addComponent(textoPrecioCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCaducidad)
                    .addComponent(labelLote))
                .addGap(7, 7, 7)
                .addComponent(esPerecible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(esLote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLote, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if (ventanaPrincipal != null) {
            ventanaPrincipal.setVisible(true);
        }
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        if(inputCodigo.getText().isEmpty() ){
            TextoError.setText("Ingrese un codigo");
            TextoError.setForeground(Color.red);
            return;
        }
        //if( esPerecible.isSelected() ){
                
        //}
        //else if( esLote.isSelected() )
        //{

        //}
        //else if( esPerecible.isSelected() && esLote.isSelected() )
        //{

        //}
        Producto nuevo = new Producto("",0,0,"",0,0);
        try{
            nuevo.setNombreProducto(inputNombre.getText());
            nuevo.setCandidadProducto(Integer.parseInt(inputCantidad.getText()));
            nuevo.setVendedor(inputVendedor.getText());
            nuevo.setPrecioCompra(Float.parseFloat(inputPrecioCompra.getText()));
            nuevo.setCodigo(Integer.parseInt(inputCodigo.getText()));
            //if( esPerecible.isSelected() ){
                
            //}
            //else if( esLote.isSelected() )
            //{
                
            //}
            //else if( esPerecible.isSelected() && esLote.isSelected() )
            //{
                
            //}

            if(tienda.getSeccion(inputSeccion.getText()).agregarProducto(Integer.parseInt(inputCodigo.getText()), nuevo)){
                this.dispose();
            }else{
                TextoError.setText("El codigo de producto ingresado ya existe");
                TextoError.setForeground(Color.red);
            }
        }catch (NumberFormatException e) {
            this.TextoError.setText("Ha ingresado un valor erroneo en una casilla");
            TextoError.setForeground(Color.red);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void esPerecibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esPerecibleActionPerformed
        // TODO add your handling code here:
        if (esPerecible.isSelected()) {
            inputCaducidad.setEditable(true);
            labelCaducidad.setText("Caducidad");
        }else
        {
            inputCaducidad.setEditable(false);
            labelCaducidad.setText("");
        }
    }//GEN-LAST:event_esPerecibleActionPerformed

    private void esLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esLoteActionPerformed
        // TODO add your handling code here:
        if (esLote.isSelected()) {
            inputLote.setEditable(true);
            labelLote.setText("Lote");
        }else
        {
            inputLote.setEditable(false);
            labelLote.setText("");
        }
    }//GEN-LAST:event_esLoteActionPerformed

    private void inputSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSeccionActionPerformed

    private void inputCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCantidadActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputVendedorActionPerformed

    private void inputPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPrecioCompraActionPerformed

    private void inputCaducidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCaducidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCaducidadActionPerformed

    private void inputLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tienda tienda = new Tienda("");
                VentanaMenuPrincipalGrafico ventanaPrincipal = new VentanaMenuPrincipalGrafico(tienda);
                new VentanaAgregarProducto(tienda,ventanaPrincipal).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoError;
    private javax.swing.JLabel TextoSeccion;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JCheckBox esLote;
    private javax.swing.JCheckBox esPerecible;
    private javax.swing.JTextField inputCaducidad;
    private javax.swing.JTextField inputCantidad;
    private javax.swing.JTextPane inputCodigo;
    private javax.swing.JTextField inputLote;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputPrecioCompra;
    private javax.swing.JTextField inputSeccion;
    private javax.swing.JTextField inputVendedor;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelCaducidad;
    private javax.swing.JLabel labelLote;
    private javax.swing.JLabel textoCantidad;
    private javax.swing.JLabel textoCodigo;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoPrecioCompra;
    // End of variables declaration//GEN-END:variables
}
