/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestioninventariomercado;

import java.awt.Color;

/**
 *
 * @author diazv
 */
public class VentanaSecciones extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSecciones
     */
    private Tienda tienda;
    public VentanaSecciones(Tienda tienda) {
        initComponents();
        this.tienda = tienda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulosecciones = new javax.swing.JLabel();
        agregarSecciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        nombreSeccionAgregar = new javax.swing.JTextField();
        eliminarSecciones = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();
        nombreSeccionaBorrar = new javax.swing.JTextField();
        botonSalir = new javax.swing.JButton();
        salirGuardar = new javax.swing.JButton();
        modificarSecciones = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonRenombrar = new javax.swing.JButton();
        nombreSeccionArenombrar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nombreSeccionRenombreFinal = new javax.swing.JTextField();
        textoError = new javax.swing.JLabel();
        textoError1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulosecciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulosecciones.setText("Editor de Secciones");

        agregarSecciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Agregar Secciones");

        jLabel4.setText("Nombre Seccion:");

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        nombreSeccionAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreSeccionAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agregarSeccionesLayout = new javax.swing.GroupLayout(agregarSecciones);
        agregarSecciones.setLayout(agregarSeccionesLayout);
        agregarSeccionesLayout.setHorizontalGroup(
            agregarSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarSeccionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(77, 77, 77))
            .addGroup(agregarSeccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agregarSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, agregarSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nombreSeccionAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        agregarSeccionesLayout.setVerticalGroup(
            agregarSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarSeccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreSeccionAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAgregar)
                .addContainerGap())
        );

        eliminarSecciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setText("Eliminar Secciones");

        jLabel7.setText("Nombre Seccion:");

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        nombreSeccionaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreSeccionaBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eliminarSeccionesLayout = new javax.swing.GroupLayout(eliminarSecciones);
        eliminarSecciones.setLayout(eliminarSeccionesLayout);
        eliminarSeccionesLayout.setHorizontalGroup(
            eliminarSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarSeccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eliminarSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(eliminarSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, eliminarSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(eliminarSeccionesLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(nombreSeccionaBorrar))
                            .addComponent(jLabel7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eliminarSeccionesLayout.setVerticalGroup(
            eliminarSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarSeccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreSeccionaBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEliminar)
                .addContainerGap())
        );

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        salirGuardar.setText("Finalizar y guardar");
        salirGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirGuardarActionPerformed(evt);
            }
        });

        modificarSecciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Cambiar nombre de Seccion");

        jLabel5.setText("Nombre Seccion a editar:");

        botonRenombrar.setText("Modificar");
        botonRenombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRenombrarActionPerformed(evt);
            }
        });

        nombreSeccionArenombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreSeccionArenombrarActionPerformed(evt);
            }
        });

        jLabel8.setText("Renombrar a:");

        nombreSeccionRenombreFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreSeccionRenombreFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modificarSeccionesLayout = new javax.swing.GroupLayout(modificarSecciones);
        modificarSecciones.setLayout(modificarSeccionesLayout);
        modificarSeccionesLayout.setHorizontalGroup(
            modificarSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarSeccionesLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(modificarSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(nombreSeccionArenombrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRenombrar)
                    .addComponent(nombreSeccionRenombreFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarSeccionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(modificarSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(17, 17, 17))
        );
        modificarSeccionesLayout.setVerticalGroup(
            modificarSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarSeccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreSeccionArenombrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreSeccionRenombreFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonRenombrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textoError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoError.setText(".");

        textoError1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoError1.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(titulosecciones)
                        .addGap(0, 163, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(agregarSecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(textoError1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modificarSecciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(eliminarSecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addComponent(textoError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(148, 148, 148)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titulosecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarSecciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificarSecciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarSecciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(textoError1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(textoError)
                    .addContainerGap(175, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        if (nombreSeccionAgregar.getText().isEmpty())
        {
            textoError1.setText("Ingrese un nombre");
            textoError1.setForeground(Color.red);
            return;
        }
        if (this.tienda.existeSeccion(nombreSeccionAgregar.getText()) )
        {
            textoError1.setText("Esta seccion ya existe");
            textoError1.setForeground(Color.red);
            return;
        }else
        {
            textoError1.setText("Seccion agregada");
            Seccion seccionnueva = new Seccion(nombreSeccionAgregar.getText());
            this.tienda.agregarSeccion(seccionnueva);
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void nombreSeccionAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreSeccionAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreSeccionAgregarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
        if (nombreSeccionaBorrar.getText().isEmpty())
        {
            textoError1.setText("Ingrese un nombre");
            textoError1.setForeground(Color.red);
            return;
        }
        if (this.tienda.existeSeccion(nombreSeccionaBorrar.getText()) )
        {
            textoError1.setText("Seccion borrada");
            this.tienda.eliminarSeccionPorNombre(nombreSeccionaBorrar.getText());
        }else
        {
            textoError1.setText("Seccion no encontrada");
            textoError1.setForeground(Color.red);
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void nombreSeccionaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreSeccionaBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreSeccionaBorrarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void salirGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirGuardarActionPerformed
        // TODO add your handling code here:
        
        // NO COMPLETADO (I NEED HELP JERE)
    }//GEN-LAST:event_salirGuardarActionPerformed

    private void botonRenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRenombrarActionPerformed
        // TODO add your handling code here:        
        if (nombreSeccionRenombreFinal.getText().isEmpty())
        {
            textoError1.setText("Ingrese un nombre");
            textoError1.setForeground(Color.red);
            return;
        }
        if (this.tienda.existeSeccion(nombreSeccionArenombrar.getText()) )
        {
            textoError1.setText("Seccion editada");
            Seccion seccionrenombrada = this.tienda.getSeccion(nombreSeccionArenombrar.getText());
            
            this.tienda.eliminarSeccionPorNombre(nombreSeccionArenombrar.getText());
            
            seccionrenombrada.setNombreSeccion(nombreSeccionRenombreFinal.getText());
            
            this.tienda.agregarSeccion(seccionrenombrada);
        }else
        {
            textoError1.setText("Seccion no encontrada");
            textoError1.setForeground(Color.red);
        }
    }//GEN-LAST:event_botonRenombrarActionPerformed

    private void nombreSeccionArenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreSeccionArenombrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreSeccionArenombrarActionPerformed

    private void nombreSeccionRenombreFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreSeccionRenombreFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreSeccionRenombreFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Tienda tienda = new Tienda("");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSecciones(tienda).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agregarSecciones;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonRenombrar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel eliminarSecciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel modificarSecciones;
    private javax.swing.JTextField nombreSeccionAgregar;
    private javax.swing.JTextField nombreSeccionArenombrar;
    private javax.swing.JTextField nombreSeccionRenombreFinal;
    private javax.swing.JTextField nombreSeccionaBorrar;
    private javax.swing.JButton salirGuardar;
    private javax.swing.JLabel textoError;
    private javax.swing.JLabel textoError1;
    private javax.swing.JLabel titulosecciones;
    // End of variables declaration//GEN-END:variables
}
